### ISSUE TITLE
[Enhancement] Allow installation of ansible roles/collections via requirements.yml

### ISSUE THREAD

**Issue by szEvEz** [telekom-mms/docker-management-container#118]
### Description

It would be nice to install ansible roles/collections via requirements.yml, so I do not have to maintain the requirements twice.

I would like to add the requirements in two ways:

- [  ] via url, e.g. 

```yaml
ansible:
  requirements:
    - https://raw.githubusercontent.com/T-Systems-MMS/ansible-role-maxscale/master/requirements.yml
```

- [  ] via adding the requirements.yml form my repository into the build context somehow

Unfortunately, the way it is documented in https://github.com/telekom-mms/docker-management-container/blob/main/docs/usage/setup_and_configuration/tool_config.md is currently not working, as

```sh
# https://github.com/telekom-mms/docker-management-container/blob/main/template.d/21_requirements#L39
ansible-galaxy install -r $URL
```

is not a functionality the ansible-galaxy command offers.
