### ISSUE TITLE
[Enhancement] Provide includable gitlab-ci template

### ISSUE THREAD

**Issue by rndmh3ro** [telekom-mms/docker-management-container#83]
### Description

While we do have [examples](https://github.com/T-Systems-MMS/docker-management-container/blob/master/examples/pipeline/gitlab-ci.yml) to setup a gitlab-pipeline for builds, I think it could help to have an include-template, that users can simply use.

Here's a first proposal on how this could look:
```
build_dmc:
  stage: docker_management_container
  image: docker:git
  services:
    - name: docker:dind
      alias: docker
  variables:
    # renovate: datasource=github-releases depName=docker-management-container
    GITHUB_DMC_TAG: 3.1.0
    SERVICE_NAME: foo
    DMC_IMAGE: $CI_REGISTRY_IMAGE/$SERVICE_NAME
  script:
    # get date for tagging the image
    - export DATE=$(date +"%F")
    # get DMC from GitHub
    - git clone --branch ${GITHUB_DMC_TAG} --depth 1 https://github.com/T-Systems-MMS/docker-management-container $CI_PROJECT_DIR/docker/docker-management-container
    # create Dockerfile with template from submodule
    - sh $CI_PROJECT_DIR/docker/docker-management-container/render.sh $CI_PROJECT_DIR/docker/$SERVICE_NAME
    # build and tag image
    - docker build -t ${DMC_IMAGE} $CI_PROJECT_DIR/docker/$SERVICE_NAME
    - docker tag $DMC_IMAGE:latest $DMC_IMAGE:${DATE} 
    # push images
    - docker push --all-tags ${DMC_IMAGE}
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $JOB == "build_dmc"
```

Users would then have to add an include for this file, set the `SERVICE_NAME`, specify a separate `docker-login`-step and optionally add tags/other stuff they need.
