### ISSUE TITLE
[Bug] Ansible Collections not installing when ansible should install per pip

### ISSUE THREAD

**Issue by avalor1** [telekom-mms/docker-management-container#85]
### Description

Ansible collections will not install when ansible is installed via pip

### Reproduction steps

Configure DMC to install ansible via pip and also install ansible collections. After this build the container.

```yaml
requirements:
  pip:
    packages:
      - ansible
    requirements:
      - https://raw.githubusercontent.com/ansible-collections/azure/v1.15.0/requirements-azure.txt

  ansible:
    collections:
      - azure.azcollection=1.15.0
      - community.crypto=2.11.0
      - t_systems_mms.acme=2.3.5
      - t_systems_mms.icinga_director=1.32.2
```

### Current Behavior

Ansible collections are tried to be installed before ansible even though the collection part comes after the pip part.

```bash
#11 [ 8/12] RUN if [ -n "${REQUIREMENTS}" ]; then       IFS=';' &&       for REQUIREMENT in ${REQUIREMENTS[@]}; do IFS='' && declare -u REQ="${REQUIREMENT}" && REQUIREMENTS_REQ=$(eval "echo \$REQUIREMENTS_${REQ}") &&       IFS=';' &&       if [ "${REQ}" = "PIP" ]; then for REQUIREMENT_REQ in ${REQUIREMENTS_PIP_PACKAGES[@]}; do pip3 install --no-cache-dir "${REQUIREMENT_REQ//=/==}"; done &&       for REQUIREMENT_REQ in ${REQUIREMENTS_PIP_REQUIREMENTS[@]}; do pip3 install --no-cache-dir -r "${REQUIREMENT_REQ}"; done; fi &&       if [ "${REQ}" = "ANSIBLE" ]; then for REQUIREMENT_REQ in ${REQUIREMENTS_ANSIBLE_ROLES[@]}; do ansible-galaxy install "${REQUIREMENT_REQ//=/,}"; done &&       for REQUIREMENT_REQ in ${REQUIREMENTS_ANSIBLE_COLLECTIONS[@]}; do ansible-galaxy collection install "${REQUIREMENT_REQ//=/:}"; done&&       for REQUIREMENT_REQ in ${REQUIREMENTS_ANSIBLE_REQUIREMENTS[@]}; do ansible-galaxy install -r "${REQUIREMENT_REQ}"; done; fi; done     fi
#11 sha256:4578ff3140b72b84a7943f3c02b949c1493dd1b224b460c659c82ba1ec078985
#11 0.330 /bin/bash: line 1: ansible-galaxy: command not found
#11 0.331 /bin/bash: line 1: ansible-galaxy: command not found
#11 0.332 /bin/bash: line 1: ansible-galaxy: command not found
#11 0.333 /bin/bash: line 1: ansible-galaxy: command not found
#11 0.984 Collecting ansible
#11 1.054   Downloading ansible-7.3.0-py3-none-any.whl (43.1 MB)
#11 1.497      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 106.1 MB/s eta 0:00:00
#11 1.794 Collecting ansible-core~=2.14.3
#11 1.804   Downloading ansible_core-2.14.3-py3-none-any.whl (2.2 MB)
#11 1.824      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 123.0 MB/s eta 0:00:00
```

### Expected Behavior

It installs the ansible collections after installing ansible via pip.

### Additional information

Wanted to use ansible from pip as it is more recent.
Versions which will get installed:
Pip: 
ansible: 7.3.0
ansible_core: 2.14.3

Apt:
ansible_core: 2.10.7
